export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_RECIPE_REJECTED = 'ADD_RECIPE_REJECTED';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const DELETE_RECIPE_FULFILLED = 'DELETE_RECIPE_FULFILLED';
